Models/AdicionarAlunoViewModel.cs
namespace AlunosWebApp.Models
{
    public class AdicionarAlunoViewModel
    {
        public string Nome { get; set; }
        public string Email { get; set; }
        public bool Ativo { get; set; }
    }
}

Models/Domain/Aluno.cs
namespace AlunosWebApp.Models.Domain
{
    public class Aluno
    {
        public Guid Id { get; set; }
        public string Nome { get; set; }
        public string Email { get; set; }
        public bool Ativo { get; set; }
    }
}

Models/ViewModels/ErrorViewModel.cs
namespace AlunosWebApp.Models.ViewModels
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/AlunosController.cs
using AlunosWebApp.Data;
using AlunosWebApp.Models;
using AlunosWebApp.Models.Domain;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace AlunosWebApp.Controllers
{
    public class AlunosController : Controller
    {
        private readonly AlunosWebAppDbContext _alunosWebAppDbContext;

        public AlunosController(AlunosWebAppDbContext alunosWebAppDbContext)
        {
            _alunosWebAppDbContext = alunosWebAppDbContext;
        }

        [HttpGet]
        public IActionResult Adicionar()
        {
            return View();
        }
        [HttpPost]

        public async Task<IActionResult> Adicionar(AdicionarAlunoViewModel adicionarAlunoViewModel)
        {
            Aluno aluno = new Aluno()
            {
                Id = Guid.NewGuid(),
                Nome = adicionarAlunoViewModel.Nome,
                Email = adicionarAlunoViewModel.Email,
                Ativo = adicionarAlunoViewModel.Ativo,
            };

            await _alunosWebAppDbContext.Alunos.AddAsync(aluno);
            await _alunosWebAppDbContext.SaveChangesAsync();

            return RedirectToAction("Adicionar");
        }
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            List<Aluno> alunos = await _alunosWebAppDbContext.Alunos.ToListAsync();
            return View(alunos);
        }
    }
}

Controllers/HomeController.cs
using AlunosWebApp.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace AlunosWebApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Alunos/Adicionar.cshtml
@model AlunosWebApp.Models.AdicionarAlunoViewModel


<h3>Adicionar Aluno</h3>
<form method="post" action="Adicionar" class="mt-5">
    <div class="mb-3">
        <label for="" class="form-label">Nome</label>
        <input type="text" class="form-control" asp-for="Nome">
    </div>
    <div class="mb-3">
        <label for="" class="form-label">E-mail</label>
        <input type="email" class="form-control" asp-for="Email">
    </div>
    <div class="form-check form-switch">
        <input class="form-check-input btn-lg" type="checkbox" role="switch" id="flexSwitchCheckChecked" asp-for="Ativo" checked>
        <label class="form-check-label" for="flexSwitchCheckChecked">Ativo</label>
    </div>

    <button type="submit" class="btn btn-primary mt-5">Adicionar</button>
</form>

Views/Alunos/Index.cshtml
@model List<AlunosWebApp.Models.Domain.Aluno>

<h3>Alunos</h3>

<table class="table table-light table-striped">
    <thead>
        <tr>
            <th>Id</th>
            <th>Nome</th>
            <th>E-mail</th>
            <th>Ativo</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var aluno in Model)
        {
            <tr>
                <td>@aluno.Id</td>
                <td>@aluno.Nome</td>
                <td>@aluno.Email</td>
                <td>@aluno.Ativo</td>
            </tr>
        }
    </tbody>
</table>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AlunosWebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AlunosWebApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AlunosWebApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Alunos" asp-action="Adicionar">Adicionar Aluno</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Alunos" asp-action="Index">Alunos</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - AlunosWebApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>